#!/bin/bash
if mountpoint -q /target; then
echo "Installing *.deb to /target"
cp /*.deb /target
else
echo "/target is not a mountpoint."
echo "You can either:"
echo "- re-run this container with -v /usr/local/bin:/target"
echo "- extract the *.deb package (located at /*.deb)"
fi
